routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware'=>'auth','prefix'=>'home'],function(){

        Route::get('/', 'HomeController@index')->name('home');

        Route::resource('linkages', 'LinkagesController', [
            'except' => [ 'destroy','show','edit','update' ]
        ]);

        Route::get('/linkages/{linkage}/delete', 'LinkagesController@destroy');
    }
);

Route::get('/{linkage}', 'RedirectionController@processRequest');

app/Linkage.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Linkage extends Model
{
    protected $fillable = ['user_id','original_link','generated_link'];

    #region MODEL CUSTOMIZATION METHODS
    public function getRouteKeyName()
    {
        return 'generated_link';
    }
    #endergion

    #region MAIN METHODS
    //method that used in views to provide path to single thread
    public function path()
    {
        return '/linkage/'.$this->generated_link;
    }
    #endregion

    #region RELATIONS METHODS
    public function user()
    {
        return $this->belongsTo(User::class);
    }
    #endregion
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    #region RELATION METHODS
    public function linkages()
    {
        return $this->hasMany(Linkage::class);
    }
    #endregion
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

class HomeController extends Controller
{
    public function index()
    {
        return view('pages.welcome-home');
    }
}

app/Http/Controllers/LinkagesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreLinkagePost;
use App\Linkage;
use App\Services\Facades\GenLink;
use Illuminate\Http\Request;
use Illuminate\Database\QueryException;

class LinkagesController extends Controller
{

    public function index()
    {
        $url = env('APP_URL');
        return view('pages.linkages')->with('url',$url);
    }

    public function destroy(Linkage $linkage)
    {
        try{
            $linkage->delete();
            session()->flash('success_message', 'Link was deleted!');
        }catch(QueryException $e){
            session()->flash('error_message', 'Link cannot be deleted');
        }
        return redirect()->back();
    }

    public function create()
    {
        return view('pages.create-link-form');
    }

    public function store(StoreLinkagePost $request)
    {
        GenLink::create($request->input('original_link'));
        session()->flash('success_message', 'Link was successfully created!');
        return redirect()->back();
    }
}

app/Http/Controllers/RedirectionController.php
<?php

namespace App\Http\Controllers;

use App\Jobs\IncrementLinkClicks;
use App\Linkage;


class RedirectionController extends Controller
{
    public function processRequest(Linkage $linkage)
    {
        IncrementLinkClicks::dispatch($linkage);
        return redirect($linkage->original_link);
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-3">
            @include('inclusions.left-side-bar')
        </div>
        <div class="col-md-9">
            @yield('right-block')
        </div>
    </div>
</div>
@endsection

resources/views/inclusions/failure-action.blade.php
@if($flash = session('error_message'))
    <div class="alert alert-danger">
        {{$flash}}
    </div>
@endif

@if (count($errors))
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
                <li>{{$error}}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/inclusions/left-side-bar.blade.php
<div class="card">
    <div class="card-header">Menu</div>

    <div class="card-body">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link level" href="/home/linkages">
                    <div class="flex">My Links</div>
                    <span class="badge badge-success">
                        {{$linkages->count()}} {{str_plural( 'link' , $linkages->count())}}
                    </span>
                </a>
            </li>
            <br>
            <li class="nav-item">
                <a href="/home/linkages/create" class="btn btn-block btn-success btn-sm" role="button">Create New Link</a>
            </li>
        </ul>
    </div>
</div>

resources/views/inclusions/success-action.blade.php
@if($flash = session('success_message'))
    <div class="alert alert-success">
        {{$flash}}
    </div>
@endif

resources/views/inclusions/top-nav-bar.blade.php
<nav class="navbar navbar-expand-md navbar-light navbar-laravel">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            {{ config('app.name', 'Laravel') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">

            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                    <li><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <style>
        body {
            padding-bottom: 10px;
        }
        .level {
            display:flex;
            align-items: center;
        }
        .flex{
            flex: 1;
        }
    </style>
</head>
<body>
    <div id="app">
        @include('inclusions.top-nav-bar')
        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/pages/create-link-form.blade.php
@extends('home')

@section ('right-block')
    <div class="card">
        <div class="card-header">My Linkages</div>

        <div class="card-body">
            @include('inclusions.success-action')
            @include('inclusions.failure-action')
            <h2>Create new link</h2>
            <form method="POST" action="{{route('linkages.store')}}">
                {{csrf_field()}}
                <div class="form-group">
                    <label for="original_link">Original Link:</label>
                    <textarea class="form-control"
                              rows="5"
                              id="original_link"
                              name="original_link"
                              placeholder="Submit original link here"
                    ></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
@endsection

resources/views/pages/linkages.blade.php
@extends('home')

@section ('right-block')
    <div class="card">
        <div class="card-header">My Linkages</div>

        <div class="card-body">
            @include('inclusions.success-action')
            @include('inclusions.failure-action')
            <h2>My links</h2>
            <table class="table table-striped" >
                <thead>
                <tr>
                    <th>Original link</th>
                    <th>Generated Link</th>
                    <th>Clicks</th>
                    <th>Delete</th>
                </tr>
                </thead>
                <tbody>
                @foreach($linkages AS $linkage)
                <tr>
                    <td>{{$linkage->original_link}}</td>
                    <td><a href="{{$url}}/{{$linkage->generated_link}}" target="_blank">{{$url}}/{{$linkage->generated_link}}</a></td>
                    <td>{{$linkage->clicks}}</td>
                    <td>
                        <a href="/home/linkages/{{$linkage->generated_link}}/delete" class="btn btn-danger btn-sm" role="button">Delete</a>
                    </td>
                </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/pages/welcome-home.blade.php
@extends('home')

@section ('right-block')
    <div class="card">
        <div class="card-header">Dashboard</div>

        <div class="card-body">
            @if (session('status'))
                <div class="alert alert-success">
                    {{ session('status') }}
                </div>
            @endif
            Hello {{Auth::user()->name}}!<br>
            You have : {{$linkages->count()}} {{str_plural( 'link' , $linkages->count())}} !<br>
            Total clicks on your {{str_plural( 'link' , $linkages->count())}} : {{$clicks}} {{str_plural( 'hit' , $clicks)}} !
        </div>
    </div>
@endsection